replicaCount: 1

image:
  repository: rc-recommunity-web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

env:
  - name: MONGO_URI
    value: mongodb://mongo:27017/rc_recommunity
  - name: FLASK_ENV
    value: development
  - name: FLASK_DEBUG
    value: "1"

volumes:
  - name: app-volume
    emptyDir: {}

volumeMounts:
  - name: app-volume
    mountPath: /app
    subPath: .

nodeSelector: {}
tolerations: []
affinity: {}
