image:
  repository: omersal/rc-recommunity
  tag: latest

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30000

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: latest
  port: 27017

env:
  MONGO_URI: "mongodb://mongodb:27017/rc_recommunity"
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"

jenkins:
  enabled: true

hpa:
  enabled: false

grafana:
  enabled: true

prometheus:
  enabled: true

argocd:
  enabled: true
  image:
    repository: argoproj/argocd
    tag: v2.11.2
  server:
    service:
      type: ClusterIP
      port: 80
  configs:
    secret:
      adminPassword: "$2a$10$e0MYzXyjpJS7Pd0RVvHwHeFuV4sTPd1q6blMt/dD4DQOG0RaFRpSG"  # bcrypt hash of "admin"

ingress:
  enabled: true
