apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rc-recommunity-helm.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rc-recommunity-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rc-recommunity-helm.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "{{ .Values.mongodb.uri }}"
            - name: FLASK_ENV
              value: "{{ .Values.env.FLASK_ENV }}"
            - name: FLASK_DEBUG
              value: "{{ .Values.env.FLASK_DEBUG }}"
