apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-recommunity
  namespace: rc-recommunity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc-recommunity
  template:
    metadata:
      labels:
        app: rc-recommunity
    spec:
      containers:
        - name: rc-recommunity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_URI
              value: "{{ .Values.env.MONGO_URI }}"
            - name: FLASK_ENV
              value: "{{ .Values.env.FLASK_ENV }}"
            - name: FLASK_DEBUG
              value: "{{ .Values.env.FLASK_DEBUG }}"
