apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-recommunity
  namespace: rc-recommunity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rc-recommunity-helm
  template:
    metadata:
      labels:
        app: rc-recommunity-helm
    spec:
      containers:
      - name: rc-recommunity
        image: omersal/rc-recommunity:latest
        ports:
        - containerPort: 8080
          name: http
