apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rc-recommunity-helm.fullname" . }}
spec:
  rules:
    - host: rc-recommunity.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rc-recommunity-helm.fullname" . }}
                port:
                  number: 8080
