apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: rc-recommunity
spec:
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
  selector:
    app: mongodb
