apiVersion: v1
kind: Service
metadata:
  name: {{ include "rc-recommunity-helm.fullname" . }}
spec:
  selector:
    app: {{ include "rc-recommunity-helm.name" . }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP 