apiVersion: v1
kind: Service
metadata:
  name: rc-recommunity-rc-recommunity-helm
  namespace: rc-recommunity
spec:
  type: NodePort
  selector:
    app: rc-recommunity-helm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001


